apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-svc
    tenant: template-tenant
  name: template-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: template-pod
  type: ClusterIP
  
